// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller";
import DropdownController from "./dropdown_controller";
import AvatarFileInputController from "./avatar_file_input_controller";
import PhoneNumberMaskController from "./phone_number_mask_controller";

application.register("alert", AlertController)
application.register("dropdown", DropdownController);
application.register("avatar-file-input", AvatarFileInputController)
application.register("phone-number-mask", PhoneNumberMaskController)
