require:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable

# Outras configurações...

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake