default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: FinMan_development
  username: postgres

test:
  <<: *default
  database: FinMan_test
  username: postgres

production:
  <<: *default
  database: FinMan_production
  username: FinMan
  password: <%= ENV["FINMAN_DATABASE_PASSWORD"] %>
